---
abstract: 'Job Queue'
author:
  - 'Sebastian Riedel <sri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Minion
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Mango: '0.24'
  Mojolicious: '4.90'
  perl: '5.010001'
resources:
  MailingList: http://groups.google.com/group/mojolicious
  bugtracker: http://github.com/kraih/minion/issues
  homepage: http://mojolicio.us
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/kraih/minion
version: '0.09'
